// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'FIREBASE_KEY_WEB',
    appId: '1:GCM_DEV:web:b3e9742bd686e96c2105f3',
    messagingSenderId: 'GCM_DEV',
    projectId: 'FIREBASE_PROJ',
    authDomain: 'FIREBASE_PROJ.firebaseapp.com',
    storageBucket: 'FIREBASE_PROJ.appspot.com',
    measurementId: 'G-W8NB7GT7Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'FIREBASE_KEY_DEV',
    appId: '1:GCM_DEV:android:aaff574616d9a9482105f3',
    messagingSenderId: 'GCM_DEV',
    projectId: 'FIREBASE_PROJ',
    storageBucket: 'FIREBASE_PROJ.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'FIREBASE_KEY_DEV_IOS',
    appId: '1:GCM_DEV:ios:a921922926c0d5082105f3',
    messagingSenderId: 'GCM_DEV',
    projectId: 'FIREBASE_PROJ',
    storageBucket: 'FIREBASE_PROJ.appspot.com',
    iosClientId: 'GCM_DEV-3mq8ueigur3t0unnieaoiquuuf3gojr1.apps.googleusercontent.com',
    iosBundleId: 'com.kotsukotsu.local',
  );
}
